/*export const table = [
    "H", "Hydrogen", "1.00794", 1, 1,
    "He", "Helium", "4.002602", 18, 1,
    "Li", "Lithium", "6.941", 1, 2,
    "Be", "Beryllium", "9.012182", 2, 2,
    "B", "Boron", "10.811", 13, 2,
    "C", "Carbon", "12.0107", 14, 2,
    "N", "Nitrogen", "14.0067", 15, 2,
    "O", "Oxygen", "15.9994", 16, 2,
    "F", "Fluorine", "18.9984032", 17, 2,
    "Ne", "Neon", "20.1797", 18, 2,
    "Na", "Sodium", "22.98976...", 1, 3,
    "Mg", "Magnesium", "24.305", 2, 3,
    "Al", "Aluminium", "26.9815386", 13, 3,
    "Si", "Silicon", "28.0855", 14, 3,
    "P", "Phosphorus", "30.973762", 15, 3,
    "S", "Sulfur", "32.065", 16, 3,
    "Cl", "Chlorine", "35.453", 17, 3,
    "Ar", "Argon", "39.948", 18, 3,
    "K", "Potassium", "39.948", 1, 4,
    "Ca", "Calcium", "40.078", 2, 4,
    "Sc", "Scandium", "44.955912", 3, 4,
    "Ti", "Titanium", "47.867", 4, 4,
    "V", "Vanadium", "50.9415", 5, 4,
    "Cr", "Chromium", "51.9961", 6, 4,
    "Mn", "Manganese", "54.938045", 7, 4,
    "Fe", "Iron", "55.845", 8, 4,
    "Co", "Cobalt", "58.933195", 9, 4,
    "Ni", "Nickel", "58.6934", 10, 4,
    "Cu", "Copper", "63.546", 11, 4,
    "Zn", "Zinc", "65.38", 12, 4,
    "Ga", "Gallium", "69.723", 13, 4,
    "Ge", "Germanium", "72.63", 14, 4,
    "As", "Arsenic", "74.9216", 15, 4,
    "Se", "Selenium", "78.96", 16, 4,
    "Br", "Bromine", "79.904", 17, 4,
    "Kr", "Krypton", "83.798", 18, 4,
    "Rb", "Rubidium", "85.4678", 1, 5,
    "Sr", "Strontium", "87.62", 2, 5,
    "Y", "Yttrium", "88.90585", 3, 5,
    "Zr", "Zirconium", "91.224", 4, 5,
    "Nb", "Niobium", "92.90628", 5, 5,
    "Mo", "Molybdenum", "95.96", 6, 5,
    "Tc", "Technetium", "(98)", 7, 5,
    "Ru", "Ruthenium", "101.07", 8, 5,
    "Rh", "Rhodium", "102.9055", 9, 5,
    "Pd", "Palladium", "106.42", 10, 5,
    "Ag", "Silver", "107.8682", 11, 5,
    "Cd", "Cadmium", "112.411", 12, 5,
    "In", "Indium", "114.818", 13, 5,
    "Sn", "Tin", "118.71", 14, 5,
    "Sb", "Antimony", "121.76", 15, 5,
    "Te", "Tellurium", "127.6", 16, 5,
    "I", "Iodine", "126.90447", 17, 5,
    "Xe", "Xenon", "131.293", 18, 5,
    "Cs", "Caesium", "132.9054", 1, 6,
    "Ba", "Barium", "132.9054", 2, 6,
    "La", "Lanthanum", "138.90547", 4, 9,
    "Ce", "Cerium", "140.116", 5, 9,
    "Pr", "Praseodymium", "140.90765", 6, 9,
    "Nd", "Neodymium", "144.242", 7, 9,
    "Pm", "Promethium", "(145)", 8, 9,
    "Sm", "Samarium", "150.36", 9, 9,
    "Eu", "Europium", "151.964", 10, 9,
    "Gd", "Gadolinium", "157.25", 11, 9,
    "Tb", "Terbium", "158.92535", 12, 9,
    "Dy", "Dysprosium", "162.5", 13, 9,
    "Ho", "Holmium", "164.93032", 14, 9,
    "Er", "Erbium", "167.259", 15, 9,
    "Tm", "Thulium", "168.93421", 16, 9,
    "Yb", "Ytterbium", "173.054", 17, 9,
    "Lu", "Lutetium", "174.9668", 18, 9,
    "Hf", "Hafnium", "178.49", 4, 6,
    "Ta", "Tantalum", "180.94788", 5, 6,
    "W", "Tungsten", "183.84", 6, 6,
    "Re", "Rhenium", "186.207", 7, 6,
    "Os", "Osmium", "190.23", 8, 6,
    "Ir", "Iridium", "192.217", 9, 6,
    "Pt", "Platinum", "195.084", 10, 6,
    "Au", "Gold", "196.966569", 11, 6,
    "Hg", "Mercury", "200.59", 12, 6,
    "Tl", "Thallium", "204.3833", 13, 6,
    "Pb", "Lead", "207.2", 14, 6,
    "Bi", "Bismuth", "208.9804", 15, 6,
    "Po", "Polonium", "(209)", 16, 6,
    "At", "Astatine", "(210)", 17, 6,
    "Rn", "Radon", "(222)", 18, 6,
    "Fr", "Francium", "(223)", 1, 7,
    "Ra", "Radium", "(226)", 2, 7,
    "Ac", "Actinium", "(227)", 4, 10,
    "Th", "Thorium", "232.03806", 5, 10,
    "Pa", "Protactinium", "231.0588", 6, 10,
    "U", "Uranium", "238.02891", 7, 10,
    "Np", "Neptunium", "(237)", 8, 10,
    "Pu", "Plutonium", "(244)", 9, 10,
    "Am", "Americium", "(243)", 10, 10,
    "Cm", "Curium", "(247)", 11, 10,
    "Bk", "Berkelium", "(247)", 12, 10,
    "Cf", "Californium", "(251)", 13, 10,
    "Es", "Einstenium", "(252)", 14, 10,
    "Fm", "Fermium", "(257)", 15, 10,
    "Md", "Mendelevium", "(258)", 16, 10,
    "No", "Nobelium", "(259)", 17, 10,
    "Lr", "Lawrencium", "(262)", 18, 10,
    "Rf", "Rutherfordium", "(267)", 4, 7,
    "Db", "Dubnium", "(268)", 5, 7,
    "Sg", "Seaborgium", "(271)", 6, 7,
    "Bh", "Bohrium", "(272)", 7, 7,
    "Hs", "Hassium", "(270)", 8, 7,
    "Mt", "Meitnerium", "(276)", 9, 7,
    "Ds", "Darmstadium", "(281)", 10, 7,
    "Rg", "Roentgenium", "(280)", 11, 7,
    "Cn", "Copernicium", "(285)", 12, 7,
    "Nh", "Nihonium", "(286)", 13, 7,
    "Fl", "Flerovium", "(289)", 14, 7,
    "Mc", "Moscovium", "(290)", 15, 7,
    "Lv", "Livermorium", "(293)", 16, 7,
    "Ts", "Tennessine", "(294)", 17, 7,
    "Og", "Oganesson", "(294)", 18, 7
  ];
*/
 export const table = [
    "H", "Hydrogen", "1.00794", 1, 1,'Hydrogen is the lightest and most abundant element in the periodic table.<\/p>\r\n\r\n<p>Hydrogen has many practical uses, most notable would be its use in the petroleum industry in various chemical reactions.<\/p>\r\n \r\n<p>Hydrogen could also be used as an energy source, either through the use of nuclear fusion or burned to run a combustion engine.',
    "He", "Helium", "4.002602", 18, 1, "Helium is both the second lightest and abundant element in the universe.<\/p>\r\n\r\n<p>Its largest use is in Cryogenics (studying the behaviour of materials at very low temperatures), however, as I'm sure you know, it is also commonly used to fill floating balloons; this effect is due to Helium atoms being lighter than Oxygen atoms.",
    "Li", "Lithium", "6.941", 1, 2, "Lithium is a highly reactive and flammable metal; this effect can be observed by cutting some Lithium open, at first it will appear 'shiny' however after a few seconds reactions with air molecules will quickly turn the colour of the Lithium into a dull grey shade.",
    "Be", "Beryllium", "9.012182", 2, 2, "Beryllium is a relatively rare element that only occurs naturally in combination with other elements in minerals.<\/p>\r\n\r\n<p>Beryllium has some interesting properties (especially when alloyed with other elements), and as such has a variety of applications in industry, most notably in the aerospace industry. However usage of Beryllium presents a number technical challenges due to the toxicity of inhaled beryllium-containing dusts",
    "B", "Boron", "10.811", 13, 2, "Boron is a low-abundance element which (in its chemically uncombined form) is found in small amounts in meteoroids, but is not found naturally on Earth. Although very pure boron can produced industrially with some difficulty.<\/p>\r\n\r\n<p>In biology, borates have low toxicity in mammals, but are more toxic to arthropods and are used as insecticides. Furthermore Boron is essential to life, small amounts of boron compounds play a strengthening role in the cell walls of all plants, making boron necessary in soils.",
    "C", "Carbon", "12.0107", 14, 2, "There are several allotropes of carbon of which the best known are graphite, diamond, and amorphous carbon. The physical properties of carbon vary widely with the allotropic form. For example, diamond is highly transparent, while graphite is opaque and black. Diamond is the hardest naturally-occurring material known, while graphite is soft enough to form a streak on paper. Diamond has a very low electrical conductivity, while graphite is a very good conductor. Under normal conditions, diamond, carbon nanotube and graphene have the highest thermal conductivities of all known materials.<\/p>\r\n\r\n<p>Carbon is the 15th most abundant element in the Earth's crust.",
    "N", "Nitrogen", "14.0067", 15, 2, "Nitrogen is a common element in the universe, estimated at about seventh in total abundance in our galaxy and the Solar System. It is also abundant on Earth, forming around 80% of Earth's atmosphere.<\/p>\r\n\r\n<p>At room temperature, it is a gas of diatomic molecules and is both colorless and odorless.<\/p>\r\n\r\n<p>The extremely strong bond in elemental nitrogen dominates nitrogen chemistry, causing difficulty for both organisms and industry in converting the N\r\n2 into useful compounds, but at the same time causing release of large amounts of often useful energy when the compounds burn, explode, or decay back into nitrogen gas.",
    "O", "Oxygen", "15.9994", 16, 2, "Oxygen is a highly reactive nonmetallic element and oxidizing agent that readily forms compounds (notably oxides) with most elements. By mass, oxygen is the third-most abundant element in the universe, after hydrogen and helium.<\/p>\r\n\r\n<p>Oxygen is an important part of the atmosphere, and is necessary to sustain most terrestrial life as it is used in respiration.",
    "F", "Fluorine", "18.9984032", 17, 2, "Fluorine is an extremely reactive and poisonous elemental gas with a pale yellow appearance. It is the lightest of the halogens and most electronegative of the elements. It is also the 24th most abundant element in the known universe.<\/p>\r\n\r\n<p>Because of the expense of refining the pure element, nearly all commercially used fluorine remains in compound form throughout its processing.",
    "Ne", "Neon", "20.1797", 18, 2, "Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.<\/p>\r\n\r\n<p>Neon gives a distinct reddish-orange glow when used in either low-voltage neon glow lamps or in high-voltage discharge tubes or neon advertising signs. The red emission line from neon is also responsible for the well known red light of helium-neon lasers. Neon is used in a few plasma tube and refrigerant applications but has few other commercial uses. It is commercially extracted by the fractional distillation of liquid air. It is considerably more expensive than helium, since air is its only source.",
    "Na", "Sodium", "22.98976...", 1, 3, "Sodium is a soft, silver-white, highly reactive metal and is a member of the alkali metals; its only stable isotope is 23Na. The free metal does not occur in nature, but instead must be prepared from its compounds<\/p>\r\n\r\n<p>Sodium is the sixth most abundant element in the Earth's crust, and exists in numerous minerals such as feldspars, sodalite and rock salt<\/p>\r\n\r\n<p>Many sodium compounds are useful, such as sodium hydroxide (lye) for soap-making, and sodium chloride for use as a de-icing agent and a nutrient (edible salt). Sodium is an essential element for all animals and some plants.",
    "Mg", "Magnesium", "24.305", 2, 3, "Magnesium is an alkaline earth metal, it is the eighth-most-abundant element in the Earth's crust and ninth most abundant in the known universe. The relative abundance of magnesium is related to the fact that it easily builds up in supernova stars from a sequential addition of three helium nuclei to carbon (which in turn is made from three helium nuclei)<\/p>\r\n\r\n<p>The free element (metal) is not found naturally on Earth, as it is highly reactive (though once produced, it is coated in a thin layer of oxide (see passivation), which partly masks this reactivity). The free metal burns with a characteristic brilliant-white light, making it a useful ingredient in flares.",
    "Al", "Aluminium", "26.9815386", 13, 3, "Aluminium is a silvery white, soft, ductile metal. Aluminium is the third most abundant element (after oxygen and silicon), and the most abundant metal, in the Earth's crust. It makes up about 8% by weight of the Earth's solid surface.<\/p>\r\n\r\n<p>Aluminium is remarkable for the metal's low density and for its ability to resist corrosion due to the phenomenon of passivation. Structural components made from aluminium and its alloys are vital to the aerospace industry and are important in other areas of transportation and structural materials.",
    "Si", "Silicon", "28.0855", 14, 3, "Silicon is a tetravalent metalloid, less reactive than its chemical analog carbon, the nonmetal directly above it in the periodic table, but more reactive than germanium, the metalloid directly below it in the table.<\/p>\r\n\r\n<p>Silicon is the eighth most common element in the universe by mass, but very rarely occurs as the pure free element in nature. It is most widely distributed in dusts, sands, planetoids, and planets as various forms of silicon dioxide (silica) or silicates. Over 90% of the Earth's crust is composed of silicate minerals, making silicon the second most abundant element in the Earth's crust (about 28% by mass) after oxygen.<\/p>\r\n\r\n<p>Pure monocrystalline silicon is used to produce silicon wafers used in the semiconductor industry, in electronics and in some high-cost and high-efficiency photovoltaic applications.",
    "P", "Phosphorus", "30.973762", 15, 3, "Phosphorus is a nonmetallic chemical element. Elemental phosphorus exists in two major forms-white phosphorus and red phosphorus-but due to its high reactivity, phosphorus is never found as a free element on Earth.<\/p>\r\n\r\n<p>The vast majority of phosphorus compounds are consumed as fertilisers. Other applications include the role of organophosphorus compounds in detergents, pesticides and nerve agents, and matches.<\/p>\r\n\r\n<p>Phosphorus is essential for life. As phosphate, it is a component of DNA, RNA, ATP, and also the phospholipids that form all cell membranes. ",
    "S", "Sulfur", "32.065", 16, 3, 'description',
    "Cl", "Chlorine", "35.453", 17, 3, 'description',
    "Ar", "Argon", "39.948", 18, 3, 'description',
    "K", "Potassium", "39.948", 1, 4, 'description',
    "Ca", "Calcium", "40.078", 2, 4, 'description',
    "Sc", "Scandium", "44.955912", 3, 4, 'description',
    "Ti", "Titanium", "47.867", 4, 4, 'description',
    "V", "Vanadium", "50.9415", 5, 4, 'description',
    "Cr", "Chromium", "51.9961", 6, 4, 'description',
    "Mn", "Manganese", "54.938045", 7, 4, 'description',
    "Fe", "Iron", "55.845", 8, 4, 'description',
    "Co", "Cobalt", "58.933195", 9, 4, 'description',
    "Ni", "Nickel", "58.6934", 10, 4, 'description',
    "Cu", "Copper", "63.546", 11, 4, 'description',
    "Zn", "Zinc", "65.38", 12, 4, 'description',
    "Ga", "Gallium", "69.723", 13, 4, 'description',
    "Ge", "Germanium", "72.63", 14, 4, 'description',
    "As", "Arsenic", "74.9216", 15, 4, 'description',
    "Se", "Selenium", "78.96", 16, 4, 'description',
    "Br", "Bromine", "79.904", 17, 4, 'description',
    "Kr", "Krypton", "83.798", 18, 4, 'description',
    "Rb", "Rubidium", "85.4678", 1, 5, 'description',
    "Sr", "Strontium", "87.62", 2, 5, 'description',
    "Y", "Yttrium", "88.90585", 3, 5, 'description',
    "Zr", "Zirconium", "91.224", 4, 5, 'description',
    "Nb", "Niobium", "92.90628", 5, 5, 'description',
    "Mo", "Molybdenum", "95.96", 6, 5, 'description',
    "Tc", "Technetium", "(98)", 7, 5, 'description',
    "Ru", "Ruthenium", "101.07", 8, 5, 'description',
    "Rh", "Rhodium", "102.9055", 9, 5, 'description',
    "Pd", "Palladium", "106.42", 10, 5, 'description',
    "Ag", "Silver", "107.8682", 11, 5, 'description',
    "Cd", "Cadmium", "112.411", 12, 5, 'description',
    "In", "Indium", "114.818", 13, 5, 'description',
    "Sn", "Tin", "118.71", 14, 5, 'description',
    "Sb", "Antimony", "121.76", 15, 5, 'description',
    "Te", "Tellurium", "127.6", 16, 5, 'description',
    "I", "Iodine", "126.90447", 17, 5, 'description',
    "Xe", "Xenon", "131.293", 18, 5, 'description',
    "Cs", "Caesium", "132.9054", 1, 6, 'description',
    "Ba", "Barium", "132.9054", 2, 6, 'description',
    "La", "Lanthanum", "138.90547", 4, 9, 'description',
    "Ce", "Cerium", "140.116", 5, 9, 'description',
    "Pr", "Praseodymium", "140.90765", 6, 9, 'description',
    "Nd", "Neodymium", "144.242", 7, 9, 'description',
    "Pm", "Promethium", "(145)", 8, 9, 'description',
    "Sm", "Samarium", "150.36", 9, 9, 'description',
    "Eu", "Europium", "151.964", 10, 9, 'description',
    "Gd", "Gadolinium", "157.25", 11, 9, 'description',
    "Tb", "Terbium", "158.92535", 12, 9, 'description',
    "Dy", "Dysprosium", "162.5", 13, 9, 'description',
    "Ho", "Holmium", "164.93032", 14, 9, 'description',
    "Er", "Erbium", "167.259", 15, 9, 'description',
    "Tm", "Thulium", "168.93421", 16, 9, 'description',
    "Yb", "Ytterbium", "173.054", 17, 9, 'description',
    "Lu", "Lutetium", "174.9668", 18, 9, 'description',
    "Hf", "Hafnium", "178.49", 4, 6, 'description',
    "Ta", "Tantalum", "180.94788", 5, 6, 'description',
    "W", "Tungsten", "183.84", 6, 6, 'description',
    "Re", "Rhenium", "186.207", 7, 6, 'description',
    "Os", "Osmium", "190.23", 8, 6, 'description',
    "Ir", "Iridium", "192.217", 9, 6, 'description',
    "Pt", "Platinum", "195.084", 10, 6, 'description',
    "Au", "Gold", "196.966569", 11, 6, 'description',
    "Hg", "Mercury", "200.59", 12, 6, 'description',
    "Tl", "Thallium", "204.3833", 13, 6, 'description',
    "Pb", "Lead", "207.2", 14, 6, 'description',
    "Bi", "Bismuth", "208.9804", 15, 6, 'description',
    "Po", "Polonium", "(209)", 16, 6, 'description',
    "At", "Astatine", "(210)", 17, 6, 'description',
    "Rn", "Radon", "(222)", 18, 6, 'description',
    "Fr", "Francium", "(223)", 1, 7, 'description',
    "Ra", "Radium", "(226)", 2, 7, 'description',
    "Ac", "Actinium", "(227)", 4, 10, 'description',
    "Th", "Thorium", "232.03806", 5, 10, 'description',
    "Pa", "Protactinium", "231.0588", 6, 10, 'description',
    "U", "Uranium", "238.02891", 7, 10, 'description',
    "Np", "Neptunium", "(237)", 8, 10, 'description',
    "Pu", "Plutonium", "(244)", 9, 10, 'description',
    "Am", "Americium", "(243)", 10, 10, 'description',
    "Cm", "Curium", "(247)", 11, 10, 'description',
    "Bk", "Berkelium", "(247)", 12, 10, 'description',
    "Cf", "Californium", "(251)", 13, 10, 'description',
    "Es", "Einstenium", "(252)", 14, 10, 'description',
    "Fm", "Fermium", "(257)", 15, 10, 'description',
    "Md", "Mendelevium", "(258)", 16, 10, 'description',
    "No", "Nobelium", "(259)", 17, 10, 'description',
    "Lr", "Lawrencium", "(262)", 18, 10, 'description',
    "Rf", "Rutherfordium", "(267)", 4, 7, 'description',
    "Db", "Dubnium", "(268)", 5, 7, 'description',
    "Sg", "Seaborgium", "(271)", 6, 7, 'description',
    "Bh", "Bohrium", "(272)", 7, 7, 'description',
    "Hs", "Hassium", "(270)", 8, 7, 'description',
    "Mt", "Meitnerium", "(276)", 9, 7, 'description',
    "Ds", "Darmstadium", "(281)", 10, 7, 'description',
    "Rg", "Roentgenium", "(280)", 11, 7, 'description',
    "Cn", "Copernicium", "(285)", 12, 7, 'description',
    "Nh", "Nihonium", "(286)", 13, 7, 'description',
    "Fl", "Flerovium", "(289)", 14, 7, 'description',
    "Mc", "Moscovium", "(290)", 15, 7, 'description',
    "Lv", "Livermorium", "(293)", 16, 7, 'description',
    "Ts", "Tennessine", "(294)", 17, 7, 'description',
    "Og", "Oganesson", "(294)", 18, 7, 'description',
  ];